const HERO_MATCHUPS = {
  // ── STR ──────────────────────────────────────────────────────────────────
  "Dragon Knight": { countered_by:["Razor","Necrolyte","Tauren Chieftain"], counters:["Storm Spirit","Puck","Weaver"], good_with:["Crystal Maiden","Witch Doctor","Ogre Magi"] },
  "Omniknight": { countered_by:["Doom","Silencer","Enigma"], counters:["Sven","Lifestealer","Phantom Assassin"], good_with:["Spectre","Huskar","Ursa"] },
  "Skeleton King": { countered_by:["Phantom Lancer","Anti-Mage","Lion","Keeper of the Light"], counters:["Tusk","Juggernaut","Earth Spirit"], good_with:["Keeper of the Light","Witch Doctor","Vengeful Spirit"] },
  "Earthshaker": { countered_by:["Clockwerk","Silencer","Tusk"], counters:["Phantom Lancer","Naga Siren","Chaos Knight"], good_with:["Dark Seer","Disruptor","Silencer"] },
  "Kunkka": { countered_by:["Huskar","Silencer","Lifestealer"], counters:["Queen of Pain","Windranger","Broodmother"], good_with:["Faceless Void","Magnus","Dark Seer"] },
  "Sven": { countered_by:["Winter Wyvern","Phoenix","Omniknight"], counters:["Phantom Lancer","Meepo","Anti-Mage"], good_with:["Magnus","Dark Seer","Io"] },
  "Tauren Chieftain": { countered_by:["Clockwerk","Lion","Ember Spirit"], counters:["Meepo","Chaos Knight","Terrorblade"], good_with:["Faceless Void","Kunkka","Dark Seer"] },
  "Axe": { countered_by:["Venomancer","Necrolyte","Shadow Demon"], counters:["Dazzle","Slark","Juggernaut"], good_with:["Lifestealer","Witch Doctor","Ancient Apparition"] },
  "Beastmaster": { countered_by:["Winter Wyvern","Earthshaker","Crystal Maiden"], counters:["Phoenix","Lifestealer","Templar Assassin"], good_with:["Drow Ranger","Dazzle","Vengeful Spirit"] },
  "Alchemist": { countered_by:["Ancient Apparition","Ursa","Lifestealer"], counters:["Nature's Prophet","Broodmother"], good_with:["Crystal Maiden","Oracle","Lich"] },
  "Centaur Warrunner": { countered_by:["Bloodseeker","Necrolyte","Kunkka"], counters:["Sniper","Windranger","Lifestealer"], good_with:["Tiny","Tusk","Dark Seer"] },
  "Clockwerk": { countered_by:["Lifestealer","Ursa","Vengeful Spirit"], counters:["Pugna","Sniper","Tinker"], good_with:["Lifestealer","Zeus","Spectre"] },
  "Io": { countered_by:["Pudge","Winter Wyvern","Ancient Apparition"], counters:["Doom","Venomancer","Undying"], good_with:["Tiny","Luna","Gyrocopter"] },
  "Treant Protector": { countered_by:["Timbersaw","Doom","Slark"], counters:["Legion Commander","Phantom Assassin","Weaver"], good_with:["Warlock","Pudge","Mirana"] },
  "Lycan": { countered_by:["Bloodseeker","Winter Wyvern","Axe"], counters:["Sniper","Invoker","Drow Ranger"], good_with:["Centaur Warrunner","Beastmaster","Dazzle"] },
  "Brewmaster": { countered_by:["Doom","Silencer","Earth Spirit"], counters:["Chaos Knight","Abaddon","Omniknight"], good_with:["Crystal Maiden","Zeus","Dazzle"] },
  "Huskar": { countered_by:["Ancient Apparition","Windranger","Necrolyte"], counters:["Crystal Maiden","Zeus","Ember Spirit"], good_with:["Abaddon","Oracle","Dazzle"] },
  "Tiny": { countered_by:["Huskar","Anti-Mage","Bloodseeker"], counters:["Terrorblade","Phantom Assassin","Crystal Maiden"], good_with:["Necrolyte","Ogre Magi","Ancient Apparition"] },
  "Pudge": { countered_by:["Abaddon","Necrolyte","Slardar"], counters:["Crystal Maiden","Shadow Fiend","Sniper"], good_with:["Dark Seer","Bane","Bloodseeker"] },
  "Earth Spirit": { countered_by:["Lifestealer","Abaddon","Bloodseeker"], counters:["Shadow Fiend","Slark","Tinker"], good_with:["Dark Seer","Lifestealer","Bloodseeker"] },
  "Spirit Breaker": { countered_by:["Bloodseeker","Puck","Chaos Knight"], counters:["Sniper","Drow Ranger","Shadow Fiend"], good_with:["Lifestealer","Spectre","Dark Seer"] },
  "Sand King": { countered_by:["Slardar","Pudge","Lifestealer"], counters:["Phantom Lancer","Chaos Knight","Puck"], good_with:["Dark Seer","Zeus","Magnus"] },
  "Lifestealer": { countered_by:["Clinkz","Ursa","Medusa"], counters:["Crystal Maiden","Nyx Assassin","Invoker"], good_with:["Slardar","Storm Spirit","Earthshaker"] },
  "Chaos Knight": { countered_by:["Axe","Lich","Leshrac"], counters:["Huskar","Ursa","Lifestealer"], good_with:["Dazzle","Keeper of the Light","Vengeful Spirit"] },
  "Doom": { countered_by:["Ancient Apparition","Dazzle","Omniknight"], counters:["Anti-Mage","Invoker","Tinker"], good_with:["Crystal Maiden","Spectre","Spirit Breaker"] },
  "Night Stalker": { countered_by:["Chaos Knight","Bloodseeker","Phantom Lancer"], counters:["Storm Spirit","Puck","Ember Spirit"], good_with:["Luna","Magnus","Vengeful Spirit"] },
  "Undying": { countered_by:["Troll Warlord","Anti-Mage","Ursa"], counters:["Spectre","Bristleback","Tiny"], good_with:["Warlock","Witch Doctor","Pugna"] },
  "Magnus": { countered_by:["Silencer","Slark","Tidehunter"], counters:["Meepo","Chaos Knight","Terrorblade"], good_with:["Phantom Assassin","Phoenix","Sven"] },
  "Tidehunter": { countered_by:["Slark","Ursa","Silencer"], counters:["Phantom Lancer","Chaos Knight","Phantom Assassin"], good_with:["Dark Seer","Templar Assassin","Keeper of the Light"] },
  "Abaddon": { countered_by:["Doom","Ancient Apparition","Silencer"], counters:["Lion","Lina","Mirana"], good_with:["Huskar","Ursa","Phantom Assassin"] },
  "Bristleback": { countered_by:["Necrolyte","Axe","Slark"], counters:["Phantom Lancer","Riki","Abaddon"], good_with:["Keeper of the Light","Oracle","Dazzle"] },
  "Timbersaw": { countered_by:["Anti-Mage","Bloodseeker","Ursa"], counters:["Chaos Knight","Meepo","Treant Protector"], good_with:["Crystal Maiden","Magnus","Keeper of the Light"] },
  "Tusk": { countered_by:["Skeleton King","Puck","Dazzle"], counters:["Crystal Maiden","Witch Doctor","Sniper"], good_with:["Axe","Omniknight","Magnus"] },
  "Phoenix": { countered_by:["Huskar","Troll Warlord","Beastmaster"], counters:["Templar Assassin","Lich","Enchantress"], good_with:["Faceless Void","Magnus","Treant Protector"] },

  // ── AGI ──────────────────────────────────────────────────────────────────
  "Anti-Mage": { countered_by:["Lion","Shadow Demon","Doom","Terrorblade"], counters:["Storm Spirit","Medusa","Invoker"], good_with:["Vengeful Spirit","Lich","Ogre Magi"] },
  "Morphling": { countered_by:["Earthshaker","Ancient Apparition","Lina"], counters:["Lifestealer","Phantom Assassin","Sniper"], good_with:["Crystal Maiden","Drow Ranger","Dazzle"] },
  "Windranger": { countered_by:["Bloodseeker","Storm Spirit","Puck"], counters:["Ursa","Lifestealer","Huskar"], good_with:["Nature's Prophet","Drow Ranger","Slardar"] },
  "Drow Ranger": { countered_by:["Storm Spirit","Centaur Warrunner","Spectre"], counters:["Bane","Puck","Huskar"], good_with:["Vengeful Spirit","Slardar","Ogre Magi"] },
  "Vengeful Spirit": { countered_by:["Phantom Lancer","Chaos Knight","Slark"], counters:["Drow Ranger","Sniper","Faceless Void"], good_with:["Drow Ranger","Sniper","Bloodseeker"] },
  "Mirana": { countered_by:["Slark","Bloodseeker","Bounty Hunter"], counters:["Crystal Maiden","Sniper","Drow Ranger"], good_with:["Bane","Shadow Demon","Axe"] },
  "Riki": { countered_by:["Bounty Hunter","Zeus","Axe"], counters:["Crystal Maiden","Puck","Keeper of the Light"], good_with:["Shadow Shaman","Bane","Lion"] },
  "Phantom Assassin": { countered_by:["Axe","Lina","Leshrac"], counters:["Juggernaut","Sniper","Drow Ranger"], good_with:["Shadow Shaman","Ogre Magi","Abaddon"] },
  "Luna": { countered_by:["Lina","Sniper","Skywrath Mage"], counters:["Undying","Lich","Slardar"], good_with:["Vengeful Spirit","Dazzle","Ogre Magi"] },
  "Templar Assassin": { countered_by:["Dark Seer","Jakiro","Leshrac"], counters:["Obsidian Destroyer","Lifestealer","Skywrath Mage"], good_with:["Slardar","Ogre Magi","Bane"] },
  "Naga Siren": { countered_by:["Lion","Zeus","Leshrac"], counters:["Bane","Ursa","Faceless Void"], good_with:["Enigma","Magnus","Dark Seer"] },
  "Phantom Lancer": { countered_by:["Zeus","Earthshaker","Leshrac"], counters:["Bane","Ursa","Drow Ranger"], good_with:["Dazzle","Crystal Maiden","Shadow Shaman"] },
  "Juggernaut": { countered_by:["Slark","Ursa","Axe"], counters:["Lich","Lifestealer","Crystal Maiden"], good_with:["Ogre Magi","Witch Doctor","Vengeful Spirit"] },
  "Clinkz": { countered_by:["Bounty Hunter","Phantom Lancer","Slardar"], counters:["Lifestealer","Juggernaut","Gyrocopter"], good_with:["Abaddon","Bane","Lion"] },
  "Bounty Hunter": { countered_by:["Slardar","Slark","Bloodseeker"], counters:["Riki","Clinkz","Weaver"], good_with:["Invoker","Tinker","Queen of Pain"] },
  "Viper": { countered_by:["Clinkz","Chaos Knight","Terrorblade"], counters:["Huskar","Spectre","Templar Assassin"], good_with:["Crystal Maiden","Faceless Void","Dazzle"] },
  "Broodmother": { countered_by:["Bloodseeker","Jakiro","Leshrac"], counters:["Drow Ranger","Bane","Nature's Prophet"], good_with:["Dazzle","Beastmaster","Shadow Shaman"] },
  "Weaver": { countered_by:["Doom","Bloodseeker","Bounty Hunter"], counters:["Lifestealer","Ursa","Undying"], good_with:["Crystal Maiden","Dark Seer","Vengeful Spirit"] },
  "Troll Warlord": { countered_by:["Razor","Axe","Obsidian Destroyer"], counters:["Lifestealer","Phoenix","Anti-Mage"], good_with:["Vengeful Spirit","Lion","Slardar"] },
  "Spectre": { countered_by:["Bloodseeker","Meepo","Necrolyte"], counters:["Sniper","Drow Ranger","Nature's Prophet"], good_with:["Warlock","Centaur Warrunner","Clockwerk"] },
  "Faceless Void": { countered_by:["Winter Wyvern","Vengeful Spirit","Omniknight"], counters:["Anti-Mage","Lifestealer","Weaver"], good_with:["Magnus","Shadow Shaman","Witch Doctor"] },
  "Slark": { countered_by:["Bloodseeker","Ancient Apparition","Doom"], counters:["Batrider","Sniper","Juggernaut"], good_with:["Ogre Magi","Shadow Shaman","Dazzle"] },
  "Gyrocopter": { countered_by:["Bloodseeker","Clinkz","Lifestealer"], counters:["Undying","Chen","Visage"], good_with:["Dark Seer","Enigma","Warlock"] },
  "Ursa": { countered_by:["Phantom Lancer","Chaos Knight","Terrorblade"], counters:["Pit Lord","Lifestealer","Timbersaw"], good_with:["Shadow Shaman","Io","Lion"] },
  "Ember Spirit": { countered_by:["Nyx Assassin","Earthshaker","Phantom Assassin"], counters:["Phantom Lancer","Chaos Knight","Sniper"], good_with:["Dark Seer","Magnus","Axe"] },
  "Terrorblade": { countered_by:["Ancient Apparition","Zeus","Lina"], counters:["Lifestealer","Ursa","Viper"], good_with:["Dazzle","Shadow Demon","Abaddon"] },
  "Arc Warden": { countered_by:["Pugna","Leshrac","Invoker"], counters:["Legion Commander","Phoenix","Templar Assassin"], good_with:["Dazzle","Beastmaster","Shadow Shaman"] },
  "Medusa": { countered_by:["Anti-Mage","Obsidian Destroyer","Sniper"], counters:["Chaos Knight","Meepo","Terrorblade"], good_with:["Vengeful Spirit","Dark Seer","Keeper of the Light"] },
  "Meepo": { countered_by:["Magnus","Winter Wyvern","Earthshaker"], counters:["Bane","Ogre Magi","Shadow Fiend"], good_with:["Beastmaster","Vengeful Spirit","Dazzle"] },

  // ── INT ──────────────────────────────────────────────────────────────────
  "Crystal Maiden": { countered_by:["Storm Spirit","Nyx Assassin","Clockwerk"], counters:["Puck","Meepo","Terrorblade"], good_with:["Bristleback","Tidehunter","Magnus"] },
  "Lina": { countered_by:["Nyx Assassin","Anti-Mage","Storm Spirit"], counters:["Enchantress","Phantom Assassin","Morphling"], good_with:["Sven","Tidehunter","Axe"] },
  "Lion": { countered_by:["Pugna","Anti-Mage","Nyx Assassin"], counters:["Puck","Weaver","Storm Spirit"], good_with:["Pudge","Ursa","Lifestealer"] },
  "Zeus": { countered_by:["Anti-Mage","Faceless Void","Nyx Assassin"], counters:["Bounty Hunter","Winter Wyvern","Enchantress"], good_with:["Ancient Apparition","Bloodseeker","Tidehunter"] },
  "Invoker": { countered_by:["Nyx Assassin","Doom","Silencer"], counters:["Skeleton King","Medusa","Spirit Breaker"], good_with:["Bloodseeker","Magnus","Faceless Void"] },
  "Pugna": { countered_by:["Nyx Assassin","Clockwerk","Pudge"], counters:["Phantom Assassin","Skywrath Mage","Enchantress"], good_with:["Shadow Shaman","Leshrac","Legion Commander"] },
  "Lich": { countered_by:["Storm Spirit","Nyx Assassin","Pugna"], counters:["Meepo","Chaos Knight","Lifestealer"], good_with:["Dragon Knight","Dark Seer","Alchemist"] },
  "Necrolyte": { countered_by:["Anti-Mage","Ancient Apparition","Nyx Assassin"], counters:["Timbersaw","Pit Lord","Bristleback"], good_with:["Abaddon","Tiny","Ancient Apparition"] },
  "Warlock": { countered_by:["Sniper","Anti-Mage","Ursa"], counters:["Meepo","Chaos Knight","Naga Siren"], good_with:["Spectre","Ember Spirit","Zeus"] },
  "Witch Doctor": { countered_by:["Slark","Anti-Mage","Nyx Assassin"], counters:["Timbersaw","Viper","Necrolyte"], good_with:["Faceless Void","Axe","Tidehunter"] },
  "Silencer": { countered_by:["Nyx Assassin","Sniper","Anti-Mage"], counters:["Magnus","Tidehunter","Enigma"], good_with:["Spectre","Centaur Warrunner","Tidehunter"] },
  "Keeper of the Light": { countered_by:["Nyx Assassin","Storm Spirit","Slark"], counters:["Weaver","Skeleton King","Dark Seer"], good_with:["Ember Spirit","Bristleback","Sven"] },
  "Shadow Shaman": { countered_by:["Sniper","Nyx Assassin","Phantom Lancer"], counters:["Puck","Weaver","Storm Spirit"], good_with:["Ursa","Juggernaut","Troll Warlord"] },
  "Death Prophet": { countered_by:["Anti-Mage","Nyx Assassin","Legion Commander"], counters:["Clockwerk","Timbersaw"], good_with:["Faceless Void","Enigma","Dazzle"] },
  "Enigma": { countered_by:["Vengeful Spirit","Rubick","Silencer","Nyx Assassin"], counters:["Phantom Lancer","Juggernaut","Lifestealer"], good_with:["Sven","Sand King","Magnus"] },
  "Ancient Apparition": { countered_by:["Anti-Mage","Silencer","Vengeful Spirit"], counters:["Huskar","Morphling","Alchemist","Io"], good_with:["Faceless Void","Venomancer","Bloodseeker"] },
  "Dark Seer": { countered_by:["Bloodseeker","Anti-Mage","Nyx Assassin"], counters:["Meepo","Chaos Knight","Templar Assassin"], good_with:["Sven","Enigma","Tauren Chieftain"] },
  "Dazzle": { countered_by:["Ancient Apparition","Axe","Silencer"], counters:["Legion Commander","Lifestealer","Necrolyte"], good_with:["Chaos Knight","Huskar","Meepo"] },
  "Obsidian Destroyer": { countered_by:["Nyx Assassin","Templar Assassin","Silencer"], counters:["Legion Commander","Timbersaw","Axe"], good_with:["Faceless Void","Shadow Shaman","Ogre Magi"] },
  "Bane": { countered_by:["Phantom Lancer","Chaos Knight","Silencer"], counters:["Storm Spirit","Puck","Ember Spirit"], good_with:["Mirana","Pudge","Witch Doctor"] },
  "Disruptor": { countered_by:["Anti-Mage","Juggernaut","Lifestealer"], counters:["Storm Spirit","Weaver","Io"], good_with:["Faceless Void","Magnus","Axe"] },
  "Jakiro": { countered_by:["Anti-Mage","Slark","Nyx Assassin"], counters:["Phantom Lancer","Meepo","Naga Siren"], good_with:["Dark Seer","Magnus","Faceless Void"] },
  "Rubick": { countered_by:["Nyx Assassin","Riki","Anti-Mage"], counters:["Pudge","Enigma","Tidehunter"], good_with:["Alchemist","Bloodseeker","Enigma"] },
  "Visage": { countered_by:["Meepo","Axe","Sniper"], counters:["Tiny","Pudge","Zeus"], good_with:["Slardar","Beastmaster","Lifestealer"] },
  "Ogre Magi": { countered_by:["Chaos Knight","Lifestealer","Phantom Lancer"], counters:["Weaver","Bloodseeker","Troll Warlord"], good_with:["Sven","Juggernaut","Skeleton King"] },
  "Skywrath Mage": { countered_by:["Nyx Assassin","Anti-Mage","Pugna"], counters:["Winter Wyvern","Enchantress","Timbersaw"], good_with:["Legion Commander","Faceless Void","Centaur Warrunner"] },
  "Oracle": { countered_by:["Axe","Ancient Apparition","Nyx Assassin"], counters:["Legion Commander","Skywrath Mage","Dark Seer"], good_with:["Huskar","Alchemist","Leshrac"] },
  "Winter Wyvern": { countered_by:["Skywrath Mage","Pugna","Ancient Apparition"], counters:["Ursa","Legion Commander","Meepo"], good_with:["Leshrac","Invoker","Dark Seer"] },
  "Batrider": { countered_by:["Nyx Assassin","Bloodseeker","Abaddon","Legion Commander"], counters:["Spectre","Lifestealer","Templar Assassin"], good_with:["Bloodseeker","Ursa","Pugna"] },
  "Tinker": { countered_by:["Nyx Assassin","Clockwerk","Spectre"], counters:["Bloodseeker","Enchantress","Phantom Assassin"], good_with:["Bounty Hunter","Faceless Void","Spirit Breaker"] },
  "Puck": { countered_by:["Nyx Assassin","Anti-Mage","Huskar"], counters:["Kunkka","Crystal Maiden","Windranger"], good_with:["Dark Seer","Magnus","Kunkka"] },
  "Leshrac": { countered_by:["Anti-Mage","Silencer","Nyx Assassin"], counters:["Phantom Lancer","Naga Siren","Chaos Knight"], good_with:["Dark Seer","Magnus","Enigma"] },
  "Nature's Prophet": { countered_by:["Spectre","Spirit Breaker","Pudge"], counters:["Lich","Treant Protector","Venomancer"], good_with:["Skywrath Mage","Invoker","Timbersaw"] },
  "Storm Spirit": { countered_by:["Anti-Mage","Nyx Assassin","Doom"], counters:["Bloodseeker","Sniper","Drow Ranger"], good_with:["Legion Commander","Dark Seer","Crystal Maiden"] },
  "Shadow Demon": { countered_by:["Sniper","Faceless Void","Doom"], counters:["Kunkka","Legion Commander","Axe"], good_with:["Slardar","Centaur Warrunner","Sand King"] },
  "Queen of Pain": { countered_by:["Anti-Mage","Nyx Assassin","Silencer"], counters:["Crystal Maiden","Keeper of the Light","Warlock"], good_with:["Bounty Hunter","Faceless Void","Axe"] },
  "Sniper": { countered_by:["Spectre","Storm Spirit","Phantom Assassin"], counters:["Dragon Knight","Medusa","Shadow Shaman"], good_with:["Drow Ranger","Vengeful Spirit","Pit Lord"] },
  "Venomancer": { countered_by:["Anti-Mage","Slark","Sniper"], counters:["Lich","Axe","Lone Druid"], good_with:["Ancient Apparition","Shadow Shaman","Pit Lord"] },
  "Nyx Assassin": { countered_by:["Anti-Mage","Bounty Hunter","Doom"], counters:["Invoker","Storm Spirit","Zeus"], good_with:["Lion","Invoker","Lina"] },
  "Razor": { countered_by:["Chaos Knight","Sniper","Terrorblade"], counters:["Phantom Assassin","Lifestealer","Spectre"], good_with:["Lion","Bane","Axe"] },
  "Shadow Fiend": { countered_by:["Faceless Void","Earth Spirit","Anti-Mage"], counters:["Lich","Gyrocopter","Meepo"], good_with:["Magnus","Dark Seer","Enigma"] },
  "Lone Druid": { countered_by:["Ursa","Chaos Knight","Lifestealer"], counters:["Crystal Maiden","Drow Ranger","Keeper of the Light"], good_with:["Vengeful Spirit","Dark Seer","Enigma"] },
  "Techies": { countered_by:["Bounty Hunter","Nature's Prophet","Invoker"], counters:["Axe","Queen of Pain","Earthshaker"], good_with:["Shadow Shaman","Enigma","Lina"] },
  "Enchantress": { countered_by:["Invoker","Axe","Phantom Assassin"], counters:["Ursa","Pit Lord","Dragon Knight"], good_with:["Nature's Prophet","Chen","Lycan"] },
  "Chen": { countered_by:["Lifestealer","Silencer","Anti-Mage"], counters:["Lycan","Broodmother","Puck"], good_with:["Nature's Prophet","Lycan","Enigma"] },
  "Slardar": { countered_by:["Phantom Lancer","Slark","Visage"], counters:["Puck","Ember Spirit","Weaver"], good_with:["Shadow Demon","Lifestealer","Lion"] },
  "Pit Lord": { countered_by:["Slark","Timbersaw","Phoenix"], counters:["Phantom Lancer","Meepo","Chaos Knight"], good_with:["Enigma","Sniper","Magnus"] },
  "Legion Commander": { countered_by:["Dazzle","Winter Wyvern","Ursa"], counters:["Phantom Assassin","Weaver","Slark"], good_with:["Skywrath Mage","Disruptor","Lion"] },
  "Bloodseeker": { countered_by:["Storm Spirit","Brewmaster","Tiny"], counters:["Anti-Mage","Dark Seer","Weaver"], good_with:["Lion","Vengeful Spirit","Disruptor"] },
};