// Auto-generated by scrape_skill_builds.js
// Values: 0=Q(ability1)  1=W(ability2)  2=E(ability3)  3=R(ult)  -1=stats
// 100 heroes scraped, 2 failed
// Generated: 2026-04-15T07:41:59.314Z

const SKILL_BUILDS = {
  "Dragon Knight": [0,2,0,1,0,3,0,2,1,1,3,1,2,2,-1,3,-1,-1], // Q-E-Q-Q-Q-R-Q-E-E-E-R-W-W-W-S-R-S-S
  "Omniknight": [0,1,0,2,0,3,0,1,1,2,3,1,-1,2,-1,3,-1,-1], // W-Q-Q-W-Q-R-Q-W-W-E-R-W-W-W-S-R-S-S
  "Skeleton King": [0,1,0,2,0,3,2,0,2,2,3,1,1,-1,1,3,-1,-1], // Q-S-Q-S-Q-R-E-Q-E-W-R-E-W-E-W-R-W-S
  "Earthshaker": [
    { label: "Support", build: [0,2,0,1,0,3,0,2,2,2,3,1,1,1,-1,3,-1,-1] },
    { label: "Core",    build: [1,2,1,0,2,3,1,1,2,2,0,3,0,0,-1,-1,-1,-1] },
  ],
  "Kunkka": [
    { label: "Support", build: [0,2,2,0,2,3,2,0,0,1,3,1,-1,-1,-1,3,-1,-1] },
    { label: "Core",    build: [1,0,1,2,1,3,1,2,2,2,1,3,-1,-1,-1,3,-1,-1/* replace with core build array */] },
  ],
  "Sven": [0,2,1,1,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-E-W-W-W-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Tauren Chieftain": [0,2,0,1,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // Q-E-Q-W-Q-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Axe": [2,0,2,0,2,3,2,0,0,1,3,-1,-1,-1,-1,3,-1,-1], // E-Q-E-E-E-R-Q-Q-Q-W-R-S-S-S-S-R-S-S
  "Beastmaster": [1,2,1,2,1,3,1,2,2,0,3,0,0,0,-1,3,-1,-1], // W-E-W-E-W-R-W-E-E-Q-R-Q-Q-Q-S-R-S-S
  "Alchemist": [0,2,0,2,0,3,0,1,2,2,3,1,-1,-1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-E-E-E-R-W-S-S-S-R-S-S
  "Clockwerk": [2,0,2,1,0,3,0,0,2,2,3,1,1,1,-1,3,-1,-1], // E-Q-E-W-Q-R-Q-Q-E-E-R-W-W-W-S-R-S-S
  "Treant Protector": [1,2,1,2,1,3,2,2,-1,-1,3,0,0,0,-1,3,-1,-1], // W-Q-W-W-W-R-E-E-E-E-R-Q-Q-Q-S-R-S-S
  "Lycan": [0,2,0,2,0,3,0,2,2,1,3,1,1,1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-E-E-W-R-W-W-W-S-R-S-S
  "Brewmaster": [0,2,0,1,0,3,0,2,2,2,3,1,1,1,-1,3,-1,-1], // Q-E-Q-W-Q-R-Q-E-E-E-R-W-W-W-S-R-S-S
  "Huskar": [1,2,1,2,1,3,1,2,2,0,3,0,0,0,-1,3,-1,-1], // W-E-W-E-W-R-W-E-E-Q-R-Q-Q-Q-S-R-S-S
  "Tiny": [0,1,1,0,1,3,1,0,0,2,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-W-R-Q-Q-Q-E-R-E-E-E-S-R-S-S
  "Pudge": [1,0,0,1,0,3,0,1,1,2,3,2,2,2,-1,3,-1,-1], // W-Q-Q-W-Q-R-Q-W-W-E-R-E-E-E-S-R-S-S
  "Earth Spirit": [1,0,1,0,2,3,1,0,0,1,3,-1,-1,-1,-1,3,-1,-1], // W-W-Q-Q-E-R-E-Q-Q-Q-R-W-W-W-S-R-S-S
  "Spirit Breaker": [0,2,0,2,0,3,0,1,1,2,3,2,1,1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-W-W-E-R-E-W-W-S-R-S-S
  "Sand King": [0,1,0,2,0,3,0,2,2,2,3,1,1,1,-1,3,-1,-1], // Q-W-Q-E-Q-R-Q-E-E-E-R-W-W-W-S-R-S-S
  "Lifestealer": [1,2,1,0,1,3,1,2,0,0,0,2,2,-1,-1,3,-1,-1], // W-Q-W-E-W-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Chaos Knight": [0,1,0,2,1,3,1,1,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-Q-E-W-R-W-W-Q-Q-R-E-E-E-S-R-S-S
  "Doom": [0,1,1,2,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-Q-W-Q-R-E-Q-W-W-R-E-E-E-S-R-S-S
  "Night Stalker": [0,1,0,2,0,3,0,2,1,2,3,1,1,-1,-1,3,-1,-1], // Q-W-Q-E-Q-R-Q-E-W-E-R-W-W-W-S-R-S-S
  "Undying": [0,1,2,2,2,3,2,1,1,1,3,0,0,0,-1,3,-1,-1], // Q-E-E-E-E-R-W-W-W-W-R-Q-Q-Q-S-R-S-S
  "Magnus": [2,0,0,1,0,3,0,1,1,1,3,-1,-1,-1,-1,3,-1,-1], // E-Q-Q-W-Q-R-Q-W-W-W-R-W-W-W-S-R-S-S
  "Tidehunter": [0,2,0,2,0,3,0,2,1,2,3,-1,1,1,1,3,-1,-1], // Q-E-Q-E-Q-R-Q-E-W-E-R-S-W-W-W-R-S-S
  "Abaddon": [
    { label: "Support", build: [1,0,1,0,1,3,1,0,0,2,3,2,2,2,-1,3,-1,-1] },
    { label: "Core",    build: [1,2,0,1,2,3,2,2,1,1,0,3,0,-1,-1,-1,-1,-1] },
  ],
  "Bristleback": [1,2,1,0,1,3,1,0,0,0,3,-1,-1,-1,-1,3,-1,-1], // W-E-W-W-W-R-Q-Q-Q-Q-R-S-S-S-S-R-S-S
  "Timbersaw": [1,2,1,0,1,3,0,1,0,0,3,2,2,2,-1,3,-1,-1], // W-E-W-Q-W-R-Q-W-Q-Q-R-E-E-E-S-R-S-S
  "Tusk": [0,1,0,1,0,3,0,1,1,2,2,3,1,1,-1,1,-1,3], // W-Q-E-Q-Q-R-Q-E-E-S-E-R-W-W-S-W-S-R
  "Phoenix": [1,0,1,2,1,3,1,2,2,-1,3,-1,-1,-1,-1,3,-1,-1], // Q-Q-W-Q-W-R-W-Q-Q-E-R-Q-Q-Q-S-R-S-S
  "Anti-Mage": [0,1,1,2,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-E-W-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Morphling": [2,0,2,0,0,3,0,1,2,2,3,1,1,1,-1,3,-1,-1], // E-Q-E-Q-Q-E-Q-R-E-W-R-W-W-W-S-R-S-S
  "Windranger": [2,0,1,1,1,0,1,0,0,3,3,2,2,2,-1,3,-1,-1], // E-Q-W-W-W-Q-W-Q-Q-R-R-E-E-E-S-R-S-S
  "Drow Ranger": [2,0,0,1,0,3,1,0,1,1,3,2,2,2,-1,3,-1,-1], // E-Q-Q-W-Q-R-W-Q-W-W-R-E-E-E-S-R-S-S
  "Vengeful Spirit": [0,1,0,2,0,3,0,1,-1,2,3,-1,-1,-1,-1,3,-1,-1], // Q-W-Q-Q-Q-R-Q-Q-Q-E-R-Q-Q-Q-S-R-S-S
  "Mirana": [0,1,0,2,0,3,0,1,1,2,3,2,2,2,-1,3,-1,-1], // E-E-E-Q-W-R-E-Q-Q-Q-R-W-W-W-S-R-S-S
  "Riki": [1,0,1,2,1,3,1,2,2,2,3,0,0,0,-1,3,-1,-1], // E-W-E-E-E-R-W-W-W-Q-R-S-S-S-S-R-S-S
  "Phantom Assassin": [0,1,0,2,0,3,0,1,1,-1,1,3,2,2,-1,2,-1,3], // Q-W-Q-E-Q-R-Q-W-W-S-W-R-E-E-S-E-S-R
  "Luna": [2,0,2,0,0,3,0,1,1,2,3,1,1,1,-1,3,-1,-1], // E-Q-E-Q-Q-R-Q-E-E-W-R-W-W-W-S-R-S-S
  "Templar Assassin": [2,0,1,2,0,3,0,1,0,2,3,-1,-1,2,-1,3,-1,-1], // E-Q-Q-W-Q-R-Q-Q-Q-Q-R-Q-Q-E-S-R-S-S
  "Phantom Lancer": [0,2,0,1,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // Q-Q-Q-W-E-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Juggernaut": [0,1,0,2,0,3,0,1,1,1,3,-1,-1,-1,-1,3,-1,-1], // Q-W-Q-E-Q-R-Q-S-S-S-R-S-S-S-S-R-S-S
  "Clinkz": [0,2,0,1,0,3,0,1,2,2,3,0,0,0,-1,3,-1,-1], // W-E-W-Q-W-R-W-E-E-E-R-Q-Q-Q-S-R-S-S
  "Bounty Hunter": [0,2,0,1,0,3,0,2,1,1,3,1,2,2,-1,3,-1,-1], // E-Q-Q-W-E-R-Q-Q-W-W-R-W-E-E-S-R-S-S
  "Viper": [0,1,2,1,1,3,1,2,0,-1,3,1,2,2,-1,3,-1,-1], // Q-W-W-Q-Q-R-E-W-Q-Q-R-W-E-E-S-R-S-S
  "Broodmother": [1,2,1,0,0,3,0,0,1,1,3,2,2,2,-1,3,-1,-1], // W-E-W-Q-Q-R-Q-Q-W-W-R-E-E-E-S-R-S-S
  "Weaver": [1,2,1,0,1,3,1,0,0,0,3,-1,-1,-1,-1,3,-1,-1], // W-E-W-Q-W-R-W-Q-Q-Q-R-Q-Q-Q-S-R-S-S
  "Troll Warlord": [1,0,1,2,1,3,1,0,0,2,3,2,-1,-1,-1,3,-1,-1], // Q-W-W-Q-W-R-W-Q-Q-E-R-Q-Q-Q-S-R-S-S
  "Spectre": [0,1,0,2,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // Q-Q-Q-W-E-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Faceless Void": [0,2,0,2,0,3,0,2,2,1,3,1,1,1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-E-E-W-R-W-W-W-S-R-S-S
  "Slark": [2,0,1,0,0,3,0,1,1,1,3,-1,2,2,-1,3,-1,-1], // W-Q-Q-Q-Q-R-Q-Q-Q-W-R-W-E-E-S-R-S-S
  "Gyrocopter": [1,0,1,0,1,3,1,0,0,2,3,2,2,2,-1,3,-1,-1], // W-Q-W-Q-W-R-W-Q-Q-E-R-E-E-E-S-R-S-S
  "Ursa": [2,1,2,0,2,3,2,1,1,1,3,0,0,0,-1,3,-1,-1], // E-W-E-W-E-R-W-E-W-Q-R-Q-Q-Q-S-R-S-S
  "Ember Spirit": [2,1,2,0,2,3,2,0,0,0,3,1,1,1,-1,3,-1,-1], // Q-W-E-E-E-R-E-Q-Q-Q-R-W-W-W-S-R-S-S
  "Naga Siren": [1,2,2,0,2,3,2,0,0,0,3,-1,-1,-1,-1,3,-1,1], // W-E-E-Q-E-R-E-Q-Q-Q-R-Q-Q-Q-S-R-S-W
  "Terrorblade": [0,2,1,1,1,3,1,2,2,2,3,0,0,0,-1,3,-1,-1], // Q-W-W-W-E-R-W-E-E-E-R-Q-Q-Q-S-R-S-S
  "Arc Warden": [2,0,2,1,2,3,2,0,0,0,3,1,1,1,-1,3,-1,-1], // E-Q-E-W-E-R-E-Q-Q-Q-R-W-W-W-S-R-S-S
  "Medusa": [0,1,1,2,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Meepo": [1,0,3,1,1,1,2,0,0,2,3,2,2,2,-1,3,-1,-1], // Q-W-R-W-W-Q-W-Q-Q-R-E-E-E-E-S-S-R-S
  "Bloodseeker": [0,2,1,2,2,3,2,1,1,0,3,0,1,1,-1,3,-1,-1], // E-Q-E-E-E-R-Q-Q-Q-W-R-W-W-W-S-R-S-S
  "Nyx Assassin": [0,2,1,0,0,3,1,0,1,1,3,2,2,2,-1,3,-1,-1], // Q-E-W-Q-Q-R-W-Q-W-W-R-E-E-E-S-R-S-S
  "Shadow Fiend": [1,0,0,1,0,1,0,1,3,2,3,2,2,2,-1,3,-1,-1], // W-Q-Q-W-Q-W-Q-W-R-E-R-E-E-E-S-R-S-S
  "Lone Druid": [0,2,0,2,0,2,0,2,3,1,1,1,1,3,-1,3,-1,-1], // Q-E-Q-E-Q-E-Q-E-R-W-W-W-W-R-R-S-R-S
  "Venomancer": [0,1,2,2,2,3,2,1,1,1,3,-1,1,-1,-1,3,-1,-1], // Q-W-W-E-Q-R-W-Q-Q-Q-R-Q-W-W-W-R-S-S
  "Sniper": [1,0,0,2,0,3,0,2,2,1,3,2,-1,-1,-1,3,-1,-1], // Q-Q-Q-W-E-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Crystal Maiden": [0,1,2,1,1,3,1,2,2,0,3,0,2,-1,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Lina": [1,0,0,2,0,3,0,2,2,2,3,1,1,1,-1,3,-1,-1], // W-Q-Q-E-Q-R-Q-E-E-E-R-W-W-W-S-R-S-S
  "Lion": [1,0,0,2,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // W-Q-Q-Q-E-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Zeus": [0,2,1,1,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Invoker": [2,3,2,1,2,0,2,0,2,0,2,0,2,3,3,1,3,1], // Q-S-Q-Q-W-Q-S-W-Q-Q-W-S-W-E-W-W-S-W
  "Pugna": [0,1,0,2,0,3,0,2,2,2,3,1,1,1,-1,3,-1,-1], // Q-W-Q-E-Q-R-Q-E-E-E-R-W-W-W-S-R-S-S
  "Lich": [0,2,0,1,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // Q-Q-Q-W-E-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Necrolyte": [0,1,0,2,0,3,0,2,2,2,3,-1,-1,-1,-1,3,-1,-1], // Q-Q-Q-W-E-R-Q-S-S-S-R-E-E-E-S-R-S-S
  "Warlock": [1,0,1,0,1,3,1,0,0,2,3,2,2,-1,-1,3,-1,-1], // W-Q-W-Q-Q-R-Q-Q-Q-Q-R-Q-Q-Q-S-R-S-S
  "Witch Doctor": [0,2,0,2,0,3,0,2,2,1,3,1,1,1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-E-E-W-R-W-W-W-S-R-S-S
  "Silencer": [1,2,2,0,2,3,0,1,0,0,3,1,1,-1,-1,3,-1,-1], // W-E-E-Q-E-R-Q-W-Q-Q-R-W-W-W-S-R-S-S
  "Keeper of the Light": [2,0,2,1,2,3,2,0,0,0,3,1,1,1,-1,3,-1,-1], // E-Q-E-W-E-R-E-Q-Q-Q-R-W-W-W-S-R-S-S
  "Shadow Shaman": [2,0,0,1,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // E-Q-Q-W-Q-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Death Prophet": [0,2,0,2,0,3,0,1,2,2,3,1,1,1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-W-E-E-R-W-W-W-S-R-S-S
  "Enigma": [1,0,1,0,1,3,1,0,2,2,3,2,2,2,-1,3,-1,-1], // W-Q-W-Q-W-R-Q-Q-W-E-R-E-E-E-S-R-S-S
  "Ancient Apparition": [0,1,0,1,0,3,0,1,1,-1,3,-1,-1,-1,2,3,-1,-1], // Q-W-Q-W-Q-R-Q-W-W-W-R-W-W-W-E-R-S-S
  "Dark Seer": [1,0,1,2,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Dazzle": [2,1,2,1,2,1,2,1,0,3,3,0,0,0,-1,3,-1,-1], // E-W-E-E-W-E-W-W-Q-R-R-Q-Q-Q-S-R-S-S
  "Obsidian Destroyer": [0,2,1,2,0,3,1,0,2,0,3,-1,-1,-1,-1,3,-1,-1], // Q-E-W-E-Q-R-W-Q-E-Q-R-Q-Q-Q-S-R-S-S
  "Bane": [1,2,1,0,1,3,1,2,2,2,3,0,0,0,0,3,-1,-1], // E-W-W-S-W-R-W-E-E-E-R-Q-Q-Q-Q-R-S-S
  "Disruptor": [0,1,2,1,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Jakiro": [0,1,0,1,0,3,0,1,2,1,3,2,2,2,-1,3,-1,-1], // E-Q-W-Q-W-R-Q-W-Q-W-R-E-E-E-S-R-S-S
  "Rubick": [0,1,1,2,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Visage": [0,1,1,2,1,3,1,0,2,2,3,-1,-1,2,-1,3,-1,-1], // W-Q-W-Q-Q-R-W-Q-Q-Q-R-Q-Q-E-S-R-S-S
  "Ogre Magi": [1,0,1,2,1,3,0,0,1,2,3,-1,-1,-1,-1,3,-1,-1], // Q-W-Q-W-Q-R-Q-W-W-E-R-W-W-W-S-R-S-S
  "Skywrath Mage": [0,1,0,2,0,3,0,1,1,1,3,2,2,2,-1,3,-1,-1], // Q-Q-Q-W-E-R-Q-W-W-W-R-E-E-E-S-R-S-S
  "Oracle": [0,2,2,1,2,3,2,0,0,0,3,1,1,1,-1,3,-1,-1], // Q-Q-E-E-E-R-E-Q-Q-Q-R-W-W-W-S-R-S-S
  "Winter Wyvern": [0,1,2,1,1,3,1,0,0,0,3,2,2,2,-1,3,-1,-1], // Q-W-W-W-E-R-W-Q-Q-Q-R-E-E-E-S-R-S-S
  "Batrider": [0,2,0,1,0,3,0,2,2,1,3,-1,-1,-1,-1,3,-1,-1], // E-Q-Q-E-Q-R-E-Q-W-E-R-S-S-S-S-R-S-S
  "Tinker": [0,1,1,2,0,3,1,2,1,2,2,0,0,3,-1,3,-1,-1], // Q-W-Q-W-Q-W-Q-W-R-Q-Q-Q-Q-R-S-R-S-S
  "Puck": [0,2,0,1,0,3,0,1,1,1,2,3,2,2,-1,-1,-1,3], // Q-E-Q-Q-Q-R-Q-W-Q-Q-S-R-E-E-E-S-S-R
  "Leshrac": [2,0,2,0,2,3,2,0,0,1,1,1,1,-1,-1,3,-1,-1], // Q-W-W-Q-W-Q-W-Q-E-R-R-E-E-E-S-R-S-S
  "Nature's Prophet": [0,1,1,2,1,3,1,2,2,2,3,0,0,0,-1,3,-1,-1], // Q-W-W-W-E-R-W-E-E-E-R-Q-Q-Q-S-R-S-S

  // ── Manually added (missing from scrape) ──────────────────────────────────
  // Q=Hoof Stomp  W=Double Edge  E=Return  R=Stampede
  "Centaur Warrunner": [0,1,2,1,1,3,1,0,0,2,3,2,2,0,-1,3,-1,-1], // E-Q-W-W-W-R-W-E-E-E-R-Q-Q-Q-R-S-S-S

  // Q=Tether  W=Spirits  E=Overcharge  R=Relocate
  "Io": [0,1,1,0,1,3,1,0,0,2,3,2,2,2,-1,3,-1,-1], // Q-W-W-Q-W-R-W-Q-Q-E-R-E-E-E-S-R-S-S

  // Q=Static Remnant  W=Electric Vortex  E=Overload  R=Ball Lightning
  "Storm Spirit": [0,2,0,2,0,3,0,2,2,1,3,1,1,1,-1,3,-1,-1], // Q-E-Q-E-Q-R-Q-E-E-W-R-W-W-W-S-R-S-S

  // Q=Disruption  W=Soul Catcher  E=Shadow Poison  R=Demonic Purge
  "Shadow Demon": [2,0,2,1,2,3,2,0,0,0,3,1,1,1,-1,3,-1,-1], // E-Q-E-W-E-R-E-Q-Q-Q-R-W-W-W-S-R-S-S

  // Q=Shadow Strike  W=Blink  E=Scream of Pain  R=Sonic Wave
  "Queen of Pain": [0,1,0,1,2,3,2,2,1,2,3,0,0,0,-1,3,-1,-1], // E-W-E-W-E-R-E-W-W-Q-R-Q-Q-Q-S-R-S-S

  // Q=Plasma Field  W=Static Link  E=Unstable Current  R=Eye of the Storm
  "Razor": [1,0,1,0,1,3,1,0,0,2,3,2,2,2,-1,3,-1,-1], // W-Q-W-Q-W-R-W-Q-Q-E-R-E-E-E-S-R-S-S

  // Q=Land Mines  W=Stasis Trap  E=Suicide Squad Attack  R=Remote Mines
  "Techies": [0,2,0,2,0,3,0,2,1,1,3,2,1,1,-1,3,-1,-1], // Q-W-Q-Q-Q-R-W-W-W-E-R-E-E-E-S-R-S-S

  // Q=Untouchable  W=Enchant  E=Nature's Attendants  R=Impetus
  "Enchantress": [1,2,0,2,2,3,2,0,1,-1,3,0,0,0,0,3,-1,-1], // W-E-E-W-E-R-E-W-W-W-R-Q-Q-Q-Q-R-S-S

  // Q=Penitence  W=Holy Persuasion  E=Divine Favor  R=Hand of God
  "Chen": [1,0,1,0,1,3,1,0,0,2,3,2,2,2,-1,3,-1,-1], // W-Q-W-W-W-R-Q-Q-Q-E-R-E-E-E-S-R-S-S

  // Q=Sprint  W=Slithereen Crush  E=Bash  R=Amplify Damage
  "Slardar": [1,0,1,2,1,3,1,0,0,2,3,2,2,-1,-1,3,-1,-1], // E-W-E-W-E-R-E-W-W-Q-R-Q-Q-Q-S-R-S-S

  // Q=Firestorm  W=Pit of Malice  E=Atrophy Aura  R=Dark Rift
  "Pit Lord": [0,1,0,2,0,3,0,2,2,2,3,1,1,1,-1,3,-1,-1], // Q-W-Q-E-Q-R-Q-E-E-E-R-W-W-W-S-R-S-S

  // Q=Overwhelming Odds  W=Press the Attack  E=Moment of Courage  R=Duel
  "Legion Commander": [0,1,0,2,0,3,1,1,1,-1,3,2,2,2,2,3,-1,-1], // Q-W-W-Q-W-R-W-Q-Q-Q-R-E-E-E-E-R-S-S
};
